version: '3.8'

services:
  saastelligence:
    build: .
    container_name: saastelligence
    ports:
      - "5000:5000"          # Main app port (for console output/debugging)
      - "8000:8000"          # Optional FastAPI endpoint
    volumes:
      - ./models:/app/models   # Mount trained models
      - ./data:/app/data       # Mount training/conversion data
      - ./logs:/app/logs       # Mount logs folder
    environment:
      - OPENAI_API_KEY=your_openai_key_here
      - META_ACCESS_TOKEN=your_meta_token
      - GOOGLE_ADS_CLIENT_ID=your_google_client_id
      - HUBSPOT_API_KEY=your_hubspot_api_key
    depends_on:
      - db
    command: sh -c "cd models && python train_intent_model.py && cd .. && uvicorn web.app:app --host 0.0.0.0 --port 8000"

  db:
    image: postgres:14
    container_name: saastelligence_db
    environment:
      POSTGRES_USER: saas_user
      POSTGRES_PASSWORD: saas_password
      POSTGRES_DB: saas_cpa_engine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"